### ISSUE TITLE
Mystical Agriculture Seed Quests

### ISSUE THREAD

**Issue by BlackholeDeath** [NordicGamerFE/Ocean-Outlast#100]
Version: [Normal] [V.56]
Description:
Trying to complete the quest line for Mystical Agricultural seeds but the required seeds are un-craftable when looked up through JEI and the only way to obtain them is by random through Loot Boxes,

Expected Result:
I would expect JEI to have a method to craft seeds rather than rely on a random low % chance drop from loot boxes.
Actual Result:
Majority of Tier 1-4 seeds are uncraftable and unable to complete quests.

Did you add additional mods?
[no]

**Comment by NordicGamerFE** [comment]
Fixed in version 58
