### ISSUE TITLE
Inventory Wiped after relog

### ISSUE THREAD

**Issue by hipsterbaby** [NordicGamerFE/Ocean-Outlast#103]
Version: Expert 57  1.12.2

Launcher: ATL

Description:
Game was bugging and items would not move in inventory (ie move from hotbar to inventory after exiting inventory would reappear in hotbar), items would not move to chests (ie when moving item in hotbar to a chest and exiting the chest menu, item would reappear in hotbar and not stay in chest). Decided a simple relog would fix this, so I exited game to main menu then relaunched the world

Expected Result:
Everything to be exactly how it was when I left and the very minor bug to be fixed

Actual Result:
Inventory, armor, baubles, traveler's backpack all gone (reduced to atoms??????)

Did you add additional mods?
no
[if yes, what mods and what versions?]

Additional information:
Happened once before in my world early into the game, decided it was just a minor bug type issue and I would put all my stuff into a chest before logging out of the world because the bug did not affect chests. However this time since I could not place my items into a chest I had to risk it, and boy did I gamble with the devil.

[If applicable, post any reports or logs related to the bug here]
[latest.log](https://github.com/NordicGamerFE/Ocean-Outlast/files/6996801/latest.log)

**Comment by NordicGamerFE** [comment]
Closed until someone else report the same issue happening again
