### ISSUE TITLE
Fluxed Electrum Seed

### ISSUE THREAD

**Issue by BlackholeDeath** [NordicGamerFE/Ocean-Outlast#104]
Version: 57

Launcher: Curseforge 

Description:
Tried to Identify Seed in Analyzer, Tried to plant on crop sticks.

Expected Result:
Seed should become a 1/1/1, And be able to be placed onto a crop to breed up to 10/10/10.

Actual Result:
Seed cannot go in Analyzer remaining unidentified. Seed cannot be placed on crop sticks.

Did you add additional mods?
No

**Comment by BlackholeDeath** [comment]
The mod Redstone Arsenal adds the Fluxed Electrum and I cannot find a matching JSON file in the Agricraft Directory.

**Comment by john13210** [comment]
still not fixed in v63
