### ISSUE TITLE
Mystical Agriculture seeds not craftable

### ISSUE THREAD

**Issue by FrediWa** [NordicGamerFE/Ocean-Outlast#105]
Version: Pack mode Easy on Ocean Outlast 57

Launcher: ATLauncher

Description:
Attempting to craft any resource seed (crafting seeds of all tiers are craftable) from Mystical Agriculture, both by JEI "Move Items" and manually but output box is empty.

Craft attempted both in AE2 crafting terminal and Vanilla crafting table.

Expected Result:
The corresponding seed can be crafted.

Actual Result:
Output box of crafting table is empty as if the recipe wasn't valid.

Did you add additional mods?
No

**Comment by NordicGamerFE** [comment]
Issue fixed in version 58
