### ISSUE TITLE
Chunk Loading Issue With 8GB Allocated

### ISSUE THREAD

**Issue by Monkeyfer** [NordicGamerFE/Ocean-Outlast#106]
Version: Hard, Ocean Outlast 57

Launcher: ATLauncher

Description:
Sailing across the ocean in search of a decent island.

Expected Result:
Chunks loading normally.

Actual Result:
Chunks not loading for more than 5 minutes. Able to walk on a single unloaded chunk, and when moving the next unloaded chunk over I fall through the world as if there was nothing and die to the void.

Did you add additional mods?
Yes
Biomes O' Plenty 1.12.2 7.0.1.2444

**Comment by NordicGamerFE** [comment]
we do not offer support with additional mods as it no longer is counted as our creation but yours if you want support remove additional mods and see if the issue still is present
