### ISSUE TITLE
Crafting conflict with bread

### ISSUE THREAD

**Issue by reddog357** [NordicGamerFE/Ocean-Outlast#107]
Version: Expert Ver. 57

Launcher: ATL

Description:
Try to craft "Bread Slices"(Tiny Progressions) in the "Cooking Table"(Cooking for Blockheads)
Try to craft "Bread Slices"(Tiny Progressions) in any crafting grid (player,crafting table, etc)

Expected Result:
get 10 "Bread Slices"(Tiny Progressions) from "Cooking Table" or crafting grid

Actual Result:
for the "Cooking Table" after clicking to select "Bread Slices" when you click again to craft nothing happens
for any crafting grid you receive 2 "Toast"(Actually Additions) from its bread recipe

Did you add additional mods?
no

Reasons this is necessary to fix, there is no way to get "Bread Slices" and thus no way to craft any sandwich recipe in the Tiny Progressions mod without cheating, and these can be eaten for progression in the food book from spice of life.

Suggestion for Solution:
Easiest - Substitute "Toast"(Actually Additions) in any recipes that call for "Bread Slices"(Tiny Progressions) and remove/blacklist "Bread Slices" in the "Food Book"(Spice of Life:Carrot Edition) or vice versa.

Easy - Change one of the recipes to a shaped recipe my sugestion would be to change "Toast"(Actually Additions) to a shaped recipe as the "Bread Slices"(Tiny Progressions) is used in more recipes.

Medium - Change "Bread Slices"(Tiny Progressions) to a shaped or shapeless recipe that requires a tool like a "Knife"(Actually Additions), "Bone Knife"(primal_tech), or "Cutting Board"(Pam's Harvest Craft), could even make each and have them give more or less Slices depending on tool grade 2-4 for "Bone Knife", 6-8 for "Knife", and 8-10 for"Cutting Board"

Coolest/Expert - Same as medium but additionally to make "Toast"(Actually Additions), you have to smelt the "Bread Slices" or put them in the "Toaster"(Cooking for Blockheads)

**Comment by NordicGamerFE** [comment]
use the arrow in the crafting grid to switch between recipes

**Comment by NordicGamerFE** [comment]
Changed recipe to work better and make less confusion
