### ISSUE TITLE
useless item from lost crate

### ISSUE THREAD

**Issue by john13210** [NordicGamerFE/Ocean-Outlast#111]
Version: 61
(dont know if this is fixed in v62 since this version doesnt have server pack)

Launcher: Curseforge 

Description:
you can get ic2 uu-matter item (not fluid) from lost crate

Expected Result:
maybe get like uu-matter bucket or cell ?

Actual Result:
useless item

**Comment by john13210** [comment]
Version: 61
(dont know if this is fixed in v62 since this version doesnt have server pack)

Launcher: Curseforge

Description:
you can get azreael's scythe with SIEVE FORTUNE from lost crate

Expected Result:
maybe switch to normal fortune ?

**Comment by NordicGamerFE** [comment]
The azreael's scythe enchantments is random and i got no control over it

**Comment by john13210** [comment]
ah ok since i got 2 of them with the same enchant i assumed it wasnt

**Comment by john13210** [comment]
"The azreael's scythe enchantments is random and i got no control over it"

i think it would show without enchant in the preview if its not set enchantment
you can see you can get it with sieve fortune if you look up what you can get from lost crates in jei

https://imgur.com/a/v3SJONn

**Comment by NordicGamerFE** [comment]
Correct my mistake. it was stuck with sieve fortune, The azreael's scythe spawns with a random enchant upon getting it I removed nbt data from it this should fix the issue
