### ISSUE TITLE
double recipes for stuff

### ISSUE THREAD

**Issue by john13210** [NordicGamerFE/Ocean-Outlast#112]
Version: 61
(dont know if this is fixed in v62 since this version doesnt have server pack)

Launcher: Curseforge

Description:
there are harder and normal recipes for stuff

Examples : (i think i will add more as i find them)
-item collector
-stellar ingot
-melodic alloy ingot

**Comment by NordicGamerFE** [comment]
I fixed the item collector but the stellar ingot and melodic alloy ingot needs to be fixed in other ways that I gonna leave for a update in the future

**Comment by john13210** [comment]
Version: 63

Launcher: Curseforge

Silver Capacitor

**Comment by john13210** [comment]
ultimate stew
2 recipes
1 very easy 

pls fix
