### ISSUE TITLE
Missing Recipe

### ISSUE THREAD

**Issue by john13210** [NordicGamerFE/Ocean-Outlast#114]
Version: 61
(dont know if this is fixed in v62 since this version doesnt have server pack)

Launcher: Curseforge

Description:
missing recipe for :
-Alchemical Imbuer
-Angel Rings

**Comment by john13210** [comment]
titanium singularity

**Comment by john13210** [comment]
-swiftwolf's rending gale (required for ring of arcane and then invincibility ring)

**Comment by john13210** [comment]
recipes for empowered blocks in multiblock

**Comment by NordicGamerFE** [comment]
recipes for empowered blocks in multiblock. Will add on a later date
-swiftwolf's rending gale is meant to be disabled I will find a work around for the issues.
-titanium singularity I'll get this fixed
-Angel Rings is meant to be disabled

**Comment by NordicGamerFE** [comment]
Just looked and yeah the Alchemical Imbuer is broken

**Comment by john13210** [comment]
creative energy cell for ae2

**Comment by john13210** [comment]
creative capacitor from thermal

**Comment by john13210** [comment]
v63
recipe for titanium singularity is still broken

**Comment by NordicGamerFE** [comment]
i am pretty sure i made it not used in any recipe so that should not matter

**Comment by john13210** [comment]
suggestion: 
hide :
ultimate singularity 
titanium singularity 
in jei
and remove recipe for them since they are unused

**Comment by john13210** [comment]
v63
recipe for empowered blocks wasnt added
