### ISSUE TITLE
Suggestion for another recipe for an item

### ISSUE THREAD

**Issue by john13210** [NordicGamerFE/Ocean-Outlast#115]
Version: 61
(dont know if this is fixed in v62 since this version doesnt have server pack)

Launcher: Curseforge

Description:
Maybe add another recipe for flint block from primal_tech

**Comment by NordicGamerFE** [comment]
Just to add some information flint blocks can be automated and is only used a couple of times In the modpack so i don't see a reason to add a new recipe for it
