### ISSUE TITLE
not removed recipes

### ISSUE THREAD

**Issue by john13210** [NordicGamerFE/Ocean-Outlast#116]
Version: 61
(dont know if this is fixed in v62 since this version doesnt have server pack)

Launcher: Curseforge

Description:
recipe wasnt removed for:
-dragon egg seeds

**Comment by john13210** [comment]
-emerald gear
-gold gear
i think these were intended to be crafted in runic altar and maybe in compactor with gearworking die later on

**Comment by john13210** [comment]
-neutronium seeds

**Comment by john13210** [comment]
-energetic silver ingot

**Comment by NordicGamerFE** [comment]
-neutronium seeds
-dragon egg seeds
-emerald gear
are ment to be craftable the way they are. the rest I will look into
