### ISSUE TITLE
Quest Bug ? Edit : My fault

### ISSUE THREAD

**Issue by john13210** [NordicGamerFE/Ocean-Outlast#120]
Version: 61
(dont know if this is fixed in v62 since this version doesnt have server pack)

Launcher: Curseforge

Description: "A Villegers Dream" Quest dont complete itself even if you have items for it

**Comment by NordicGamerFE** [comment]
Thank you for reporting issues, For future reference it would be nice if you say what chapter the said quest is in as there is over 1000+ quests and sometimes its hard to find a quest if I forgotten the quest

**Comment by NordicGamerFE** [comment]
Make sure you make the correct emerald armor

**Comment by john13210** [comment]
you should add description saying to check if you crafted armor from tiny progression or maybe even better acceptiong armor from both mods
