### ISSUE TITLE
Something for gaia spirits

### ISSUE THREAD

**Issue by john13210** [NordicGamerFE/Ocean-Outlast#122]
Version: 61
(dont know if this is added in v62 since this version doesnt have server pack)

Launcher: Curseforge

Description:
A bit Expensive Multiblock for gaia spirits automation since you CANT automate killing of the gaia guardian

OR

Expensive duping recipe (you know 1 spirit and some items = more spirits)

**Comment by NordicGamerFE** [comment]
This modpack is not about all automation i want a pack where you still have to grind a bit even towards endgame

**Comment by john13210** [comment]
did you forgot about the other recipe for stellar alloy ?
