### ISSUE TITLE
Semi Useless Item from Avaritia

### ISSUE THREAD

**Issue by john13210** [NordicGamerFE/Ocean-Outlast#123]
Version: 61
(dont know if this is added in v62 since this version doesnt have server pack)

Launcher: Curseforge

Description: Enhancement Crystal has only 3 uses when crafted with
-infinity breastplate for noclip
-infinity helmet for night vision (lame)
-sword for looting 10 (you dont need to do that for high lv of looting)
so its kinda not worth crafting maybe you could add recipe for something with it or add some more uses for it

**Comment by NordicGamerFE** [comment]
Agreed 100%. Tho its hard to find new use-cases for something like that I think its better to just make it cheaper
