### ISSUE TITLE
Recipe for an item ( ae2 )

### ISSUE THREAD

**Issue by john13210** [NordicGamerFE/Ocean-Outlast#133]
Version: 63

Description:

I would like to have access to inscriber name press

What does it do ?

It can rename items with inscriber and it could make some autocrafting possible
for example you want to craft something but there are 2 of the same item but placed in 2 slots so if you request to craft that item and interface will put 2 items in 1 slot so thats a problem ...

examples:
structure frame tier 6
plant oil
witches' stitching
golden thread

and some other stuff

**Comment by NordicGamerFE** [comment]
You can already make this using a Certus/Nether knife. Will add quest
