### ISSUE TITLE
Modpack won't load

### ISSUE THREAD

**Issue by grannyd16** [NordicGamerFE/Ocean-Outlast#14]
Version: Expert 47

Description:
Attempting to Load the modpack on both twitch curse launcher or AT launcher

Expected Result:
The modpacks loads then enters the title screen

Actual Result:
The modpack dosn't load past 95% Completed : Ender Tweaker, and clicking the window shows it to be not responding
![image](https://user-images.githubusercontent.com/36170362/87170317-154ffc80-c2c9-11ea-8919-d0f82bb4186f.png)

Did you add additional mods?
No

**Comment by NordicGamerFE** [comment]
I need logs. use https://hastebin.com/

**Comment by grannyd16** [comment]
[2020-07-10-1.log.gz](https://github.com/NordicGamerFE/Ocean-Outlast/files/4906539/2020-07-10-1.log.gz)

Managed to get it working by using the previous version

**Comment by NordicGamerFE** [comment]
try to start the game with xms at 4000m also i told you to use https://hastebin.com/ this is the last time i download a file

**Comment by grannyd16** [comment]
The file was too big for hastebin and pastebin, and i will try that

**Comment by RiftsSirDrake** [comment]
I'm seeing the same issue, the modpack appears to stall at 95% on EnderTweaker. It doesn't seem to actually crash, but simply runs painfully slowly regardless of memory set for the pack. This is what the end of the log looks like when it hits that 95% mark: https://hastebin.com/kaxivihawo.sql, before that is several hundred lines of the "Potentially Dangerous alternative prefix".

**Comment by NordicGamerFE** [comment]
I need the entire log to get all the information i need if the entire log don't fit use two hastebin's. did you try to start the game with xms at 4000mb?

**Comment by RiftsSirDrake** [comment]
Looks like the size of the log is 3+ hastebins in size, loaded it into git: https://raw.githubusercontent.com/RiftsSirDrake/Temp_Stuff/master/ocean_Outlast_Log

I've tried 4000mb and 8000mb (8000 is what I normally set for bigger packs) without luck. I've also tried in both twitch and ATL to rule out anything launcher specific causing troubles.

Looking at the log, you'll see this line: [07:40:14] [Client thread/INFO]: UniDict: All 7 Integrations took 71ms to finish. at load stage PostInit

and then a delay of over an hour before things start moving again for a few minutes, before again hitting a stop and going non-responsive.

**Comment by NordicGamerFE** [comment]
Could i have the ATLauncher log also

**Comment by NordicGamerFE** [comment]
ok so i read the log and your issue is with Optifine

**Comment by RiftsSirDrake** [comment]
Here is the ATL version of the log https://raw.githubusercontent.com/RiftsSirDrake/Temp_Stuff/master/ocean_outlast_ATL_log

I haven't added optifine to the ATL version, but still seeing the same issue. Gets to 95% Ender Tweaker and sits. I've left it for a bit over 30 minutes stuck, I'll give it another hour, see if it eventually makes any progress, and upload an updated log if it does.

**Comment by z3nth10n** [comment]
Well, I can verify this problem too. This is my actual log file
[2020-07-13-1.log.gz](https://github.com/NordicGamerFE/Ocean-Outlast/files/4913046/2020-07-13-1.log.gz)
And this is what is happens once I remove Optifine and I try to load everything again:
[latest.log](https://github.com/NordicGamerFE/Ocean-Outlast/files/4913080/latest.log)

**Comment by NordicGamerFE** [comment]
i dont download files sorry

**Comment by NordicGamerFE** [comment]
@xChaosityx

**Comment by RiftsSirDrake** [comment]
Took about 2hrs to load, but I've found if I leave it sit, the modpack does eventually load on twitch or ATL, with or without optifine.

Here is the ATL Log from when it finally loaded: https://raw.githubusercontent.com/RiftsSirDrake/Temp_Stuff/master/ocean_outlast_ATL_2hrs_loaded

**Comment by Elsewere** [comment]
hi to all im new here , i trie to donwload on the atl launcher but i have this error , did anyone had the same error and could fix ?

[14/7/2020 22:17:51 PM] java.lang.NullPointerException
	at com.atlauncher.data.minecraft.loaders.forge.ForgeLoader.getMainClass(ForgeLoader.java:179)
	at com.atlauncher.workers.InstanceInstaller.determineMainClass(InstanceInstaller.java:590)
	at com.atlauncher.workers.InstanceInstaller.install(InstanceInstaller.java:416)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:205)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:1)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
tkx very much in advance

**Comment by Elsewere** [comment]
NordicGamerFE tkx very much , sorry for the wrong room of issue :)

**Comment by Elsewere** [comment]
Hello again, can you help or not really , because its been 4 days and not even an idea of what its happening with the mod on atlauncher . the ocean outlast its the only one that i CANT donwload . tkx in advance

**Comment by NordicGamerFE** [comment]
@grannyd16 @z3nth10n try the new update. reopen if issue presists

**Comment by Elsewere** [comment]
i di and same error , im post here the log one second

**Comment by Elsewere** [comment]
[34WzFvsJ.txt](https://github.com/NordicGamerFE/Ocean-Outlast/files/4943076/34WzFvsJ.txt)
