### ISSUE TITLE
Runs out of memory with 16GB of memory allocated

### ISSUE THREAD

**Issue by Sage-King** [NordicGamerFE/Ocean-Outlast#140]
Version: Easy 63

Launcher: ATL

Description:
Playing the game with a friend on a world and the game crashes. Sometimes the game won't even launch before crashing. Runs out of memory during the mod loading phase. Uses 15.7 of my 15.9GB available.  When I try to enter a world, it drops 3GB of active memory using only 12.7 out of 15.9GB.  Launching the game starts at 4GB immediately consumed and during mod loading it slowly ramps up to 15.7GB. I have had multiple crashes and nothing seems to consistently run it out of memory. Has crashed multiple times on launch and sometimes after about 2 minutes of playing with my friend.  I have played solo and it worked fine.

Crash Report:
[Uploaded to ATL because it was too big for hastebin](https://paste.atlauncher.com/view/42aa50d8-8b09-4366-af46-4f2c27fb901b)

Did you add additional mods?
No

Here are ATL's settings when I launch Ocean Outlast
![atl_settings_for_crash_report](https://user-images.githubusercontent.com/67001456/146167902-00156aa3-d5da-4ba7-8cde-73c94778bf70.JPG)

**Comment by Sage-King** [comment]
I believe I have solved the issue. I lowered the initial memory to 512 and lowered the max memory and permgen to 6144 bytes(six gigabytes). I have had no problems since fixing them.

**Comment by NordicGamerFE** [comment]
Simple case of too much of the good stuff. Also you only have 16 gb of ram
so dedicating all your ram means that Minecraft will use 16 if it can but
when it asks for the ram its already in use since you only got 16 and all
processes on a PC use ram
