### ISSUE TITLE
Time has stopped

### ISSUE THREAD

**Issue by Daniel-Avo** [NordicGamerFE/Ocean-Outlast#142]
Version: EASY newest

Launcher: ATL

Description:
Nothing I just played

Expected Result:
Time has stopped, even when you go to bed night does not changing to day.

Actual Result:
Time is stopped

Did you add additional mods?
no

I found no logs

I think it happend when I have enlarged the RAM space for this instance.

**Comment by NordicGamerFE** [comment]
Please provide latest.log in the logs folder

**Comment by Daniel-Avo** [comment]
[LOGS.txt](https://github.com/NordicGamerFE/Ocean-Outlast/files/7785909/LOGS.txt)
