### ISSUE TITLE
Particles shutting off randomly

### ISSUE THREAD

**Issue by dkiller790** [NordicGamerFE/Ocean-Outlast#144]
Version: [Expert] [Version 63]

Launcher: [AT Launcher]

Description:
Randomly while playing all particles will essentially shut off. This includes the laser beam generated by the atomic reconstructor and all of the botania mod particles. The only way I've found to fix the particles is to completely close the pack and relaunch it. Just exiting the world and restarting does not fix it.

Expected Result:
Particles to work continually.

Actual Result:
No particles

Did you add additional mods?
No additional mods.

**Comment by NordicGamerFE** [comment]
pretty sure the laser beam is not part of the particle system so this is weird. Make sure all your graphical drivers are up to date

**Comment by dkiller790** [comment]
Okay I'll update them must be something local because I've discovered it only happens when I leave the game paused for a little while.
