### ISSUE TITLE
Moonlight forge Recipe for infinity ingot broke?

### ISSUE THREAD

**Issue by Blazier1** [NordicGamerFE/Ocean-Outlast#145]
Version: [Easy/Expert] [Version number] Expert v63

Launcher: [ATL, Curseforge or Others like MultiMC]  Curseforrge

Description:
[Describe what actions you have taken to caused the bug]
Put Neutronium Ingots and Infinity Catalyst into the moonlight forge at night to craft the infinity ingot

![2022-01-30_03 24 02](https://user-images.githubusercontent.com/79803455/152253263-937a9e28-bbde-4036-80e4-9d91d4501871.png)

Expected Result:
[Describe the result you expected]
to receive an Infinity Ingot from the forge

Actual Result:
[Describe the actual result]
Recieved an enhancement crystal 
![2022-01-30_03 24 49](https://user-images.githubusercontent.com/79803455/152262638-34485eca-0381-4764-bfc1-e574fd030f0a.png)

Did you add additional mods?
[yes/no]  no
[if yes, what mods and what versions?]

[If applicable, post any reports or logs related to the bug here]
I was just playing on the Pixil gaming server and this error happened 3 times. Its like it is somehow confusing the neutronium ingot for the crystal ingot in the enhancement recipe.

**Comment by Rhobox** [comment]
Playing on a private unchanged Ocean Outlast v.63 server, same issue
Pack mode HARD
