### ISSUE TITLE
Server crash due to "Wormhole"

### ISSUE THREAD

**Issue by JulianVennen** [NordicGamerFE/Ocean-Outlast#159]
Version: V66

Launcher: Server files downloaded from CurseForge

Description:
When you download the server files, run the forge installer and attempt to start the server, it will crash.
This is caused by the wormhole mod, which doesn't seem to properly work on servers.
Removing the mod solves the issue, this will however most likely cause issues with clients that didn't remove the mod.

Log: https://mclo.gs/7qoHFAY
Crash Report: https://mclo.gs/eONU7Or

Did you add additional mods? no

**Comment by NordicGamerFE** [comment]
I am having some problems with my java at the moment so I have not been able to test the server files before I do updates, Could you check if the older version of wormhole works?

**Comment by JulianVennen** [comment]
The previous version (1.1.10) works.
I also created an issue in the mod's bug tracker: https://github.com/SuperMartijn642/Wormhole/issues/36

**Comment by NordicGamerFE** [comment]
Thank you, I will get this fixed.

**Comment by NordicGamerFE** [comment]
Update is live hopefully fixing all the crash issues.
