### ISSUE TITLE
world not loading, all blocks invisible but mobs spawn

### ISSUE THREAD

**Issue by webbtj55** [NordicGamerFE/Ocean-Outlast#160]
Version: 64.1
Launcher: ATL

Description:
i load into the world and it just is completely invisible. im not good with tech or things like that but this hasnt happened before. waiting does nothing, ive waited for 2 hours 

Did you add additional mods?
no

**Comment by NordicGamerFE** [comment]
Hey @webbtj55 I am currently not feeling great so i wont be able to help you today, But to get stuff moving please attach latest.log

**Comment by webbtj55** [comment]
how do i attach the latest.log?

**Comment by webbtj55** [comment]
take ur time btw, i hope you feel better!

**Comment by NordicGamerFE** [comment]
@webbtj55 simply drag the file into github or use https://gist.github.com
