### ISSUE TITLE
Tech Reborn Not Producing Ores

### ISSUE THREAD

**Issue by NicoTms** [NordicGamerFE/Ocean-Outlast#162]
Version: [Easy/Expert] [Version number]
Easy, 66.1
Launcher: [ATL, Curseforge or Others like MultiMC]
ATL
Description:
[Describe what actions you have taken to caused the bug]
building a full void ore miner produces no ores
upon further inspection JEI has no recipes that show void ore miner production

Expected Result:
[Describe the result you expected]
Void or miner produces ores

Actual Result:
[Describe the actual result]
building a full void ore miner produces no ores

Did you add additional mods?
[yes/no]
[if yes, what mods and what versions?]
yes in actual world
no, when testing if this was a me problem(i redownloadd and tested the base game V63 works but V66.1-V65 ddon't work)

[If applicable, post any reports or logs related to the bug here]

**Comment by soadrage7654** [comment]
I ran into this as well on V.66.1. The config data for the void miners is malformed on this version (some strings are missing their end quotation marks). You'll need to manually manually fix the JSON data for each of the void ore miners in config\environmentaltech\multiblocks\void_miner\ore (github won't let me attach JSON files, sorry). I verified that this fixes all 6 tiers of void ore miners.

Specifically, if you look at config\environmentaltech\multiblocks\void_miner\ore\tier_1.json, you'll see that some color strings (white, brown, yellow, etc.) have an open quote but not a closing quote, e.g.

"target": "brown,
should be replaced with
"target": "brown",

Do this for all the affected lines in all 6 tier files and you should be good to go.
