### ISSUE TITLE
Block of enchanted metal

### ISSUE THREAD

**Issue by Bowlesy01** [NordicGamerFE/Ocean-Outlast#163]
Version: [Easy/Expert] [Version number]

Launcher: [ATL, Curseforge or Others like MultiMC]

Description:
[Describe what actions you have taken to caused the bug]

Expected Result:
[Describe the result you expected]

Actual Result:
[Describe the actual result]

Did you add additional mods?
[yes/no]
[if yes, what mods and what versions?]

[If applicable, post any reports or logs related to the bug here]

**Comment by NordicGamerFE** [comment]
this is issue is blank i cant do anything with  it
