### ISSUE TITLE
Instance not opening

### ISSUE THREAD

**Issue by WcaleNieMisker** [NordicGamerFE/Ocean-Outlast#164]
Version: 66.1

Launcher: MultiMC

Description:
Instance is not opening.

Crash Report:
[https://paste.ee/p/UrOYS](https://paste.ee/p/UrOYS)

Did you add additional mods?
no

**Comment by NordicGamerFE** [comment]
Please switch to using jdk 8.

**Comment by WcaleNieMisker** [comment]
how to switch it to only this instance?

**Comment by NordicGamerFE** [comment]
edit instance, settings, java installation. mc 1.12.2 needs java 8
