### ISSUE TITLE
Crushed after rebind wasd buttons 

### ISSUE THREAD

**Issue by karuiEden** [NordicGamerFE/Ocean-Outlast#167]
Version: 0.67
Launcher: Prism Launcher

Description:
I can't move in game with wasd, I rebinded w button on w and game crashed.

Crash Report:
https://hastebin.com/share/iwujaweney.php)](https://hastebin.com/share/iwujaweney.php

Did you add additional mods?
No

**Comment by B4kingb** [comment]
I have a similar issue where only the w key to move forward does not work. using the w key to type while in my inventory works fine though

**Comment by karuiEden** [comment]
I fixed that, I use KDE Plasma 6 and first layout was non-English
