### ISSUE TITLE
Time not progressing-

### ISSUE THREAD

**Issue by Girfan3198** [NordicGamerFE/Ocean-Outlast#169]
Version: Easy (?) 

Launcher: Curseforge

Description:
it happens whenever I load into a world time- doesn't progress. I tried changing the time to kick start everything but time physically doesn't progress.

Expected Result:
Day/Night cycle

Actual Result:
permalock at 00:00 or whatever time you set it to.

Did you add additional mods?
No fresh install from the update.

**Comment by NordicGamerFE** [comment]
try /gamerule doDaylightCycle true and check if that might be your problem

**Comment by Girfan3198** [comment]
that did not work even if I set time then do it.
