### ISSUE TITLE
Backpacks in transmutation table broken

### ISSUE THREAD

**Issue by tijgerlady** [NordicGamerFE/Ocean-Outlast#171]
Version: [Easy/Expert] [Version number]
Easy . didn't check expert   version 72A
Launcher: [ATL, Curseforge or Others like MultiMC]
Cursforge
Description:
[Describe what actions you have taken to caused the bug]
Putting the iron backpack in the transmutation table gives a broken item
putting higher tier backpacks in the transmutation table doesnt show at all
Expected Result:
[Describe the result you expected]
That it will show in the transmutatioon table correct

Actual Result:
[Describe the actual result]
broken or not showes at all

Did you add additional mods?
[yes/no] no
[if yes, what mods and what versions?]

[If applicable, post any reports or logs related to the bug here]
![image](https://github.com/user-attachments/assets/ae66dc33-59d6-46cb-a29c-c90000b228ce)

**Comment by NordicGamerFE** [comment]
I cant fix this, Iron Backpacks store their type in NBT and ProjectE does not take NBT into account just like mekanism cables and tanks will always be tier 1 in ProjectE Iron Backpacks will be nothing
![image](https://github.com/user-attachments/assets/3afee18f-d9c8-441e-a09c-cda154e8f6a8)
