### ISSUE TITLE
[Suggestion] Add XU2-Patcher mod. Bug Fixes for Extra Utilities 2!

### ISSUE THREAD

**Issue by Kanzaji** [NordicGamerFE/Ocean-Outlast#173]
Version: Most likely both 😅
I have a suggestion for a Mod.

Description:
Hi there! Full disclaimer - I'm a developer of IC2 and XU2 Patchers 😋 So I'm bit of a biased here, but mayyybee you will find the XU2 Patcher interesting 👀

https://www.curseforge.com/minecraft/mc-mods/xu2-patcher

The mod does essentially the same thing as IC2 Patcher - it fixes bugs in an abandoned AAR mod, this time Extra Utilities 2.
Except some old bugs, the biggest thing for the players is making the screens work again with Imgur (as Imgur changed the policy and now requires trickery to make it work with 3rd party stuff).

**Comment by NordicGamerFE** [comment]
I appreciate the grind blud gotta put bread on the table, all jokes aside already have it lined up for the next update :P

**Comment by NordicGamerFE** [comment]
Would you mind making it so your mod can be downloaded via third party launchers?

**Comment by Kanzaji** [comment]
Oh right I completely forgot about it 😅 Was meant to switch it some time ago.
Update: Done ❤️
