### ISSUE TITLE
79A Crash Issue

### ISSUE THREAD

**Issue by karavolt** [NordicGamerFE/Ocean-Outlast#175]
Version: [Expert] [79A]

Launcher: [curseforge]

Description:
upadate 78 -> 79. then load singleplay server. and get crash.

Crash Report:
https://mclo.gs/lhCV8qC

Did you add additional mods?
[no]

**Comment by NordicGamerFE** [comment]
if you restart the game do you still get the issue?

**Comment by karavolt** [comment]
oh.
i restart a game, when loading wolrd alert poped. 
8 missing mod warning..

so game is not crash anymore.
