### ISSUE TITLE
Problem with @Improvable Skills

### ISSUE THREAD

**Issue by AdamantineAmmonite** [NordicGamerFE/Ocean-Outlast#18]
Version: Expert / current version 48

Description:
I tried to use the book that comes with @Improvable Skills and while withdrawing xp from the bank to level my skills i ran into a problem.

Expected Result:
Xp should've been taken from the XP Bank.

Actual Result:
Checking the XP Bank it now reads "too much" and my actual xp value is some crazy negative number.
I see no way to reset my xp or the XP Bank. Currently i cannot use anything that uses xp (anvil) since i can't even gather xp from killing mobs for example. My experience points are completely broken.

Did you add additional mods?
no

**Comment by danstols** [comment]
I have the same problem, but this problem was even when i disable improvable skills. How can I fix it. I have already reinstalled the instance and try a new world
