### ISSUE TITLE
I can’t lose hunger 

### ISSUE THREAD

**Issue by ashermania** [NordicGamerFE/Ocean-Outlast#20]
I even tried to give myself the hunger effect it didn’t work this really take away from the survival part please help

**Comment by stijndp** [comment]
Was already slightly mentioned at the end of [Issue 19](https://github.com/NordicGamerFE/Ocean-Outlast/issues/19).
The player has a foodExhaustionLevel value. It increases from 0 to 4 by performing certain actions. When it's at 4, it does -1 on the player's foodSaturationLevel and then resets back to 0.

In my save file my foodExhaustionLevel is -18338,78. And my saturation will not go down until it reaches 4.
I can regen 1528 hearts before my saturation will go down again. Or sprint 183427 blocks.

Could you confirm that you saw strange food values happening after being attacked by parasites? I think that's where it happened to me and it would give @NordicGamerFE an idea where to start looking.

**Comment by NordicGamerFE** [comment]
If anyone wanna add to this issue feel free i got no idea what the source is nor does my team

**Comment by AnomalyXIII** [comment]
just updated the game and it seems like you all may have over done the fix and now my character has the never ending hunger, starving to death. I even tried to see if it would continue into a new game and started game starving.

**Comment by NordicGamerFE** [comment]
Think issue has been fixed
