### ISSUE TITLE
PrimalTech did not appear in the game

### ISSUE THREAD

**Issue by Breninja05** [NordicGamerFE/Ocean-Outlast#22]
Version: [Easy/Expert] [Version number]

Description:
i loaded in the game and played the first few steps but could not progress due to all items in primaltech not being present within the recipes 

Expected Result:
ive played primal tech before so despite not finding the recipe i put in the materials from memory

Actual Result:
i did not get the item and i double checked the recipe from a wiki but i got it right then i checked to see if any primaltech items were present and when i did a mod search there was nothing

Did you add additional mods?
i added no mods
[if yes, what mods and what versions?]

[If applicable, post any reports or logs related to the bug here]

**Comment by NordicGamerFE** [comment]
Duo to not getting a version number i cant go any further please provide a version number

**Comment by NordicGamerFE** [comment]
Closed duo to inactivity
