### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by neonbro** [NordicGamerFE/Ocean-Outlast#23]
When clicking on New instance on the AT launcher it wont finish installing. 
Latest Version of The launcher.

this is the error im getting
https://paste.atlauncher.com/view/acdfc4fa

any idea's?

Edit: installing using the Twitch launcher seems to be working, might be AT Launcher thats having issues.

**Comment by NordicGamerFE** [comment]
Have you tried to start the launcher in administrator

**Comment by neonbro** [comment]
yes i did try launching in administrator and i still got that issue. but however when i installed the pack with the twitch launcher it worked fine.
