### ISSUE TITLE
Item render in JEI crash

### ISSUE THREAD

**Issue by AlenaDragonrider** [NordicGamerFE/Ocean-Outlast#27]
Version: [Easy/Expert] [Version number]
I believe we are using 49.HFI it was the most recent update for the modpack till this point. it is running on AtLauncher. I'm not sure about the Easy or Expert thing though.
Description:
[] I am LAN lining a server so me and my partner can play together. I have almost 8G of RAM allocated to run the modpack and the recommended was 6 so I wasn't expecting to have issues. I was looking up possible ways to get rid of extra flint generated from sifting and my partner was messing around with ledstone fluxducts trying to power our empowerer. I had been getting spurts of lag but they seemed to be tied with the fact that inventory sorting and the item lookup for JEI were booth tied to the same key so we changed it. This was just biased on checking the console and seeing what it was catching on.

Crash Report:
[] https://hastebin.com/raw/xuyuzowipu

Did you add additional mods?
No

**Comment by NordicGamerFE** [comment]
can you reproduse the issue? or did it only happen once?

**Comment by AlenaDragonrider** [comment]
Its only happened the once, and today I updated to the latest version. But we play quite a bit so if it happens again I will add that crash report. This was my first time being able to figure out how to send one in, and it was not the only crash we had. I actually had one before this where the link it gives you wouldn't work.

**Comment by NordicGamerFE** [comment]
Closed reopen if issue happends again
