### ISSUE TITLE
Problems with latest update

### ISSUE THREAD

**Issue by wingmaster870** [NordicGamerFE/Ocean-Outlast#30]
Ever since installing the V.50.ATL.HF.2 my game has been experiencing sever lag issues and the Auto Jump feature in the Options menu is disabled so that Auto Jump is always on even though I have it set to Off in the Options menu.  Is there any way I can fix these issues?  I have no issues with other mod packs.  Hopefully the powers that be are aware of these issues and are working on a solution to be soon released.  I really enjoy the game but these issues are making it frustrating to play.  Any suggestions are welcome.  My system....Intel I7-8700 3.70GHx (12 CPU's). 32 Gig memory, RTX 2080ti.  16 Gig memory dedicated to Java memory.

**Comment by NordicGamerFE** [comment]
Need logs and a screenshot of a laggoggles run of the world for 30 secounds

**Comment by NordicGamerFE** [comment]
Closed duo to inactivity
