### ISSUE TITLE
Ingots from crates belong to the wrong mods

### ISSUE THREAD

**Issue by cenodis** [NordicGamerFE/Ocean-Outlast#31]
Version: Expert V.50

Description:
Open Crates and receive metal ingots via random chance.

Expected Result:
Ingots should be from the same mod as other sources, like when casting them via the smeltery (i.e. Thermal Foundation ingots)

Actual Result:
Ingots are from a variety of mods such as Silver from Bewitchment and Copper from IC2. These dont stack with the TF ingots making them annoying to store.

Did you add additional mods?
no

**Comment by cenodis** [comment]
Same happens with ingots gotten from lootbags.

**Comment by NordicGamerFE** [comment]
Added recipes to convert ingots to TF ingots
