### ISSUE TITLE
Recipe for smelting redstone dust does not line up with recipe for casting redstone ingots

### ISSUE THREAD

**Issue by cenodis** [NordicGamerFE/Ocean-Outlast#32]
Version: Expert V.50

Description:
Smelting one redstone dust in the smeltery yields 100 mB of destabilized redstone. Casting one redstone ingot requires 144 mB. This makes it difficult to cast without leftovers. JEI reports a smelting recipe that yields 144 mB for each redstone dust but this seems to go unused.

Expected Result:
One redstone ingot should be equal to 100 mB of destabilized redstone.

Actual Result:
One redstone ingot is equal to 144 mB of destabilized redstone.

Did you add additional mods?
no

**Comment by NordicGamerFE** [comment]
Fixed in V.53
