### ISSUE TITLE
Insane Ram Usage 

### ISSUE THREAD

**Issue by chewwbakaa** [NordicGamerFE/Ocean-Outlast#33]
Version: Peaceful 12.2

Description:
I made a default world and traveled a little bit. after finding a suitable island i made a little camp with a few sieves a couple bonsai planters all of a sudden when i was sieving my ram usage spiked to 10k usage and wouldn't go down i cant figure out why

Did you add additional mods?
No
[if yes, what mods and what versions?]

[If applicable, post any reports or logs related to the bug here]

**Comment by NordicGamerFE** [comment]
Please provide a log

**Comment by NordicGamerFE** [comment]
Might have been fixed in V.52 please check and report back if its still a problem keep please check that you have java 8 261 or 251 before reopening
