### ISSUE TITLE
Blast furnace multiblock bug

### ISSUE THREAD

**Issue by Mirerew** [NordicGamerFE/Ocean-Outlast#35]
Version: /Expert - V.51

Description:
The recipe for "normal item input" cant be crafted and when i used creative mod to give the block to me , the multiblock keeps saying "missing normal item input"

Expected Result:
Working blast furnace
Actual Result:
[Describe the actual result]

Did you add additional mods?
yes
Schematica

[If applicable, post any reports or logs related to the bug here]

**Comment by NordicGamerFE** [comment]
update if the issue still remains reopen issue
