### ISSUE TITLE
pure daisy

### ISSUE THREAD

**Issue by EnderW502** [NordicGamerFE/Ocean-Outlast#38]
Version: easy I think idk about version number, I'm playing the latest version though

Description:
I made the pure daisy and placed it down in the middle of some wood and stone that were in a circle around the daisy

Expected Result:
particles and eventually living stone and wood

Actual Result:
after 25 minutes nothing happened. there isn't even the particle effect around the daisy. i didn't even know there were supposed to be particles until I looked it up.

Did you add additional mods?
no

**Comment by Isla-Liu** [comment]
the recipe changed, did u tried greatwood plank and stoneburnt?
