### ISSUE TITLE
Unable to craft iron pressure plate

### ISSUE THREAD

**Issue by Anakardian** [NordicGamerFE/Ocean-Outlast#40]
Version: Expert V.51

Description:
Trying to craft the iron pressure plate does not work in the vanilla crafting table and the crafting table from tinkers.
Clicking the plus button to place the items in the crafting grid from jei dos not work.
Manually placing the items does not work.

Expected Result:
Would craft the iron pressure plate

Actual Result:
nothing, not possible to craft

Did you add additional mods?
No

**Comment by NordicGamerFE** [comment]
Update
