### ISSUE TITLE
Hunger issue on Nodecraft Server

### ISSUE THREAD

**Issue by TheShadyFlame** [NordicGamerFE/Ocean-Outlast#42]
Version: V51

Description:
Logged into Nodecraft server and immediately encounter instant hunger loss. 

Did you add additional mods?
[yes/no]
The server wanted the Debugtools and knobcontrol. 

[If applicable, post any reports or logs related to the bug here]

**Comment by TheShadyFlame** [comment]
fixed by removing those two mods listed above from client and the server. Can you remove from future server updates?

**Comment by NordicGamerFE** [comment]
Its been fixed in ATL.HF1 and Twitch 51.HF1
