### ISSUE TITLE
Void Metal Seeds

### ISSUE THREAD

**Issue by alexslash65** [NordicGamerFE/Ocean-Outlast#43]
Version: [Easy/Expert] [Version number]
V.51.ATL.HF2
still don't know if it's Easy or Expert.
Description:
[Describe what actions you have taken to caused the bug]
The Void Metal Seeds are not compatible with the crop sticks
Expected Result:
[Describe the result you expected]
I wanted to scan it and plant it.
Actual Result:
[Describe the actual result]
I could only plant it without Agricraft crop sticks.
Did you add additional mods?
[yes/no]
[if yes, what mods and what versions?]
yes mousetweaks.

[If applicable, post any reports or logs related to the bug here]

**Comment by NordicGamerFE** [comment]
Fixed in V.52 (Comming soon)

**Comment by JSteenberg** [comment]
@NordicGamerFE i have the same problem with thaumium seeds and inferium seeds.
