### ISSUE TITLE
Increase shape limit for 3d printer

### ISSUE THREAD

**Issue by cenodis** [NordicGamerFE/Ocean-Outlast#46]
Version: Expert and Easy
I have a suggestion for a config change.

Description:
The 3d printer from OpenComputers is able to print arbitrary microblocks similar to Chisel and Bits. Unfortunately its default config only allows shapes composed of up to 24 axis-aligned boxes. Each block can contain up to 16\*16\*16 (4096) voxels which makes it nearly worthless compared to C&B (excluding a few instances where interactive blocks are needed).

I would suggest raising this limit somewhat to make it a more viable option. My recommendation would be either 128 (half a block side) or 256 (a full block side). Since one printed block can have 2 states 128 shapes would probably be the better option to balance size and usability.
To make even more intricate designs C&B would remain uncontended but for simpler microblock builds OC could compete due to its potential for automation compared to C&B.

Limit can be adjusted in `config/opencomputers/settings.conf`:
```
printer {
    maxShapes=24
```

**Comment by NordicGamerFE** [comment]
Finished for the next update
