### ISSUE TITLE
Add Extra Bit Manipulation

### ISSUE THREAD

**Issue by cenodis** [NordicGamerFE/Ocean-Outlast#47]
Version: Easy and Expert
I have a suggestion for a Mod.

Description:
This mods adds more tools to manage Chisel and Bits blocks, such as the ability to rotate them and create certain shapes easier. Also adds the ability to chisel cosmetic armor.
Like C&B this mod is almost purely cosmetic and has no noticable impact on the games balance.

[https://www.curseforge.com/minecraft/mc-mods/extra-bit-manipulation](https://www.curseforge.com/minecraft/mc-mods/extra-bit-manipulation)

**Comment by NordicGamerFE** [comment]
Added to the next update
