### ISSUE TITLE
Sieve, skystone bug?

### ISSUE THREAD

**Issue by JSteenberg** [NordicGamerFE/Ocean-Outlast#48]
Version:Version: ExpertV51

Description:
The auto sieve does not produce what is expected when sieving skystone with dia 

Expected Result:
I should get: 1 Charged certus crystal, 1 standart certus crystal and 1 certus crystal seed

Actual Result:
I get 1 Charged certus crystal and 1 certus crystal seed

Did you add additional mods?
no

<img width="1440" alt="Skærmbillede 2020-09-09 kl  21 22 15" src="https://user-images.githubusercontent.com/60323164/92644090-114d5480-f2e3-11ea-9dd9-2550cccd0175.png">
<img width="1440" alt="Skærmbillede 2020-09-09 kl  21 27 24" src="https://user-images.githubusercontent.com/60323164/92644193-448fe380-f2e3-11ea-82cf-f13657888496.png">

**Comment by JSteenberg** [comment]
<img width="534" alt="Skærmbillede 2020-09-09 kl  21 28 35" src="https://user-images.githubusercontent.com/60323164/92644299-6d17dd80-f2e3-11ea-803d-7a3c525c1a65.png">

**Comment by WaterMelwin** [comment]
normal sieve gives me the right stuff. Maybe its a auto sieve thing?

**Comment by john13210** [comment]
+1 sand also doesnt give you stuff from fossils and arch
gravel doesnt give you stygian iron dust

(v61)
