### ISSUE TITLE
All upgrade disapearing from my Mob Crusher (Industrial Foregoing)

### ISSUE THREAD

**Issue by mbbk** [NordicGamerFE/Ocean-Outlast#51]
Version: Easy V.52.ATLHF1

Description:
I used Mob Crusher and also Mob Slaughter Factory from Industrial Foregoing before it for my mob farm and everytime when i check if machines are fine i see always upgrade disapeared in it. They are also receiving energy from a Flux plug, maybe it have something to do with that bug because my others Industrial Foregoing machine dont have this problem and they are not getting energy from Flux network mod.

Expected Result:
Being able to put upgrade in my Mob Crusher without them disapearing evey 2 hours

Actual Result:
Always when i check if the machine are working i see them stopped and all upgrade slot returned to blank so i always need to put new upgrade.

Did you add additional mods?
no

![2020-09-16_05 29 00](https://user-images.githubusercontent.com/31296724/93294814-dddf5e00-f7eb-11ea-9caf-2bb2b12d7a39.png)
![2020-09-16_06 55 39](https://user-images.githubusercontent.com/31296724/93294816-de77f480-f7eb-11ea-896f-cfc72fc21862.png)

**Comment by NordicGamerFE** [comment]
Could you please run the system in some other way then the flux plug to see if it reproduses the issue?

**Comment by mbbk** [comment]
I did that 20 minute ago, i will post update here if it seem fine

**Comment by mbbk** [comment]
Ok now i checked again without Flux plug,  instead it was directly connected with my cable and again, all upgrade disapeared and the fluid essence stop being extracted by the ender io conduit.

Now i will test again by removing the Ender tank collecting the fluid and put directly the Black hole tank to see if the problem come from this

**Comment by mbbk** [comment]
Ok now it look like issue solved by changing the fluid system. I think my mistake was to put ender io double fluid conduit with Crusher collecting essence and Vacuum XP collecting experience and both going in the same ender tank even if at the ender tank i had what i needed to handle that. So for now no more upgrade disapearing
