### ISSUE TITLE
Golden Lasso

### ISSUE THREAD

**Issue by NordicGamerFE** [NordicGamerFE/Ocean-Outlast#53]
Version: V.52

Description:
Golden Lasso takes the mob but actually never moves the mob when placed down they will seem normal for a secound but teleport back to spot of origin

Expected Result:
For the golden lasso to take the mob and place it down without issues

Actual Result:
Golden Lasso takes the mob but when placed down the mob will teleport back to spot of origin

Did you add additional mods?
no

**Comment by Isla-Liu** [comment]
i got this problem too
