### ISSUE TITLE
Crafting recipes

### ISSUE THREAD

**Issue by keaton81** [NordicGamerFE/Ocean-Outlast#54]
Version:normal, V.52

There is a problem with the meta data for some crafting recipes such as the energy condenser and ender tank. 

Expected result: for them to craft.
Actual result: they did not craft.

Speculation for reasons that they did not craft:
If you take energy out of a ultimate induction cell and try and use it to craft the energy condenser, it will not let you use it/ craft with it.

If you take mekanism fluid tanks out of a transmutation table, they will not work in the crafting recipe for the ender tank. 

No additional mods were added.

**Comment by NordicGamerFE** [comment]
This is a problem with how mekanism has its id's i got no controll over these parameters and therefor dont know how i would fix it outside of modifying the base code of mekanism itself
