### ISSUE TITLE
Generic Seeds Only From Hunter's Crates?

### ISSUE THREAD

**Issue by remclave** [NordicGamerFE/Ocean-Outlast#56]
**Version:** 
Expert V.53.1

**Description:**
When opening quest reward chest, the only item it drops are Generic Seeds from Agricraft. Is this intended? They will not plant on tilled farmland nor do they work with cropsticks. I also found no optional uses (like a recipe to convert it to something useful?)

**Expected Result:**
Unknown. With a name like generic, I would hope for SOME interaction within the game. However this is not the case.

**Actual Result:**
Takes up inventory space. Can only be thrown away.

**Did you add additional mods?** 
NO.

No reports or logs generated so not available.

**Comment by NordicGamerFE** [comment]
intended
