### ISSUE TITLE
Universe Dialer crashes the game with NullPointerException

### ISSUE THREAD

**Issue by Vamael** [NordicGamerFE/Ocean-Outlast#57]
[latest.log](https://github.com/NordicGamerFE/Ocean-Outlast/files/5351891/latest.log)

**Comment by NordicGamerFE** [comment]
Use a digital means of sharing your log i do not download files (you can use options as paste.gg)

**Comment by Vamael** [comment]
https://paste.gg/p/anonymous/ed4ccd2c57794bc68dcb545d9b798b61

**Comment by NordicGamerFE** [comment]
I think the player LameDuck is in a bad place you need to find a way to get this said player away from hes current spot

**Comment by remclave** [comment]
Same thing happened the moment I attempted to "look" at the device in my hotbar. 
https://pastebin.com/HzGQErzn

**Comment by Isla-Liu** [comment]
get this problem too,
bad thing is player will get it in looting bag or quest chest
if player open it and have badluck got Universe Dialer
Their client have chance to crash too
need remove it from playerdata nbt :<

**Comment by NordicGamerFE** [comment]
Remove anuis from the mods folder
