### ISSUE TITLE
Journey Map Issue

### ISSUE THREAD

**Issue by Jinxhoney1113** [NordicGamerFE/Ocean-Outlast#59]
Version: [Easy/Expert] [Version number]

Description:
I changed the settings in Journey Map so that I could see the mini icons of the various mobs instead of the little dots, and it shut down the internal server and now I cant get back into the game.

Did you add additional mods?
No

[If applicable, post any reports or logs related to the bug here]

**Comment by NordicGamerFE** [comment]
closed duo to incorrect use of format
