### ISSUE TITLE
Blacklist Agricraft channels from JEI by default

### ISSUE THREAD

**Issue by cenodis** [NordicGamerFE/Ocean-Outlast#6]
JEI can cause a crash when it attempts to render the Agricraft channels, tanks and valves in its item view. A possible mitigation for these crashes is to hide these items from JEI with its blacklist function. This does not completely prevent them from being rendered by JEI but since the crash is somewhat rare its usually good enough to not be a serious issue.

See also AgriCraft/AgriCraft#1170

**Comment by NordicGamerFE** [comment]
Hidden and added quests for channels and tanks
