### ISSUE TITLE
Craft Tweaker Mod recipes no longer being supported on my server?

### ISSUE THREAD

**Issue by Roo0s** [NordicGamerFE/Ocean-Outlast#60]
Expert V.5.3.1

The server went crashed one night while I was online and since then the tweaked recipes no longer work and have reverted back to original vanilla ones. JEI is still going off of the tweaked recipe's so I assume that the problem lies with the Craft tweaker2 mod. What kind of actions can I take to repair the server and preferably without rollback?
Thanks.

**Comment by NordicGamerFE** [comment]
reinstall the server and keep the world
