### ISSUE TITLE
PlusTic Mirion didn't Alloy

### ISSUE THREAD

**Issue by Isla-Liu** [NordicGamerFE/Ocean-Outlast#64]
Version: OceanOutlast Expert V.53.1

Description:
I put the TerraSteelx2 Cobalt Orex1 ManaSteelx2 Elementiumx2 Clear Glassx2 in smeltry,but it just keep in smeltry not going alloy.

Expected Result:
Should get mirion.

Actual Result:
Material just stay in smeltry, nothing happend.

Did you add additional mods?:
Sponge 7.3.0
MmmMmmMmmMmm 1.14
--most server side function mod below--
DiscordIntegration 3.0.5
Dynmap 3.1
LagGoggles 4.11-92
TickProfile 0.10
unloader 1.2.0

[If applicable, post any reports or logs related to the bug here]
no logs/reports

**Comment by NordicGamerFE** [comment]
Can you do it in singleplayer?

**Comment by Isla-Liu** [comment]
> Can you do it in singleplayer?

nope,singleplayer still the same, uncraftable
i guess maybe that is cause by Moar Tinker and PlusTic?
they both have added botania tinker component
but i always only can make Moar Tinker part if they both exist
maybe this also affect on molten liquid
ex like
recipe need PlusTic Elementium liquid, but only can get Moar Tinker's.

**Comment by Isla-Liu** [comment]
is Right, if use PlusTic Molten Liquid, then it craftable
but normaly drop these material just get Moar Tinker Liquid, it Uncraftable
and another question is Moar Tinker and PlusTic component(pickaxe head, tool rod) has conflict

**Comment by Isla-Liu** [comment]
> is Right, if use PlusTic Molten Liquid, then it craftable
> but normaly drop these material just get Moar Tinker Liquid, it Uncraftable
> and another question is Moar Tinker and PlusTic component(pickaxe head, tool rod) has conflict

Only elementium will be MoarTinker's motlen liquid let recipe break
