### ISSUE TITLE
Issue With Wireless redstone

### ISSUE THREAD

**Issue by CronixGaming** [NordicGamerFE/Ocean-Outlast#65]
Version: [Easy/Expert] [Version number]

Description:Keep getting issues when trying to load the mod pack up
[Describe what actions you have taken to caused the bug]

Expected Result:
[Describe the result you expected]

Actual Result:
[Describe the actual result]

Did you add additional mods?
[yes/no]
[if yes, what mods and what versions?]

[If applicable, post any reports or logs related to the bug here]

**Comment by NordicGamerFE** [comment]
Closed duo to not following the format
