### ISSUE TITLE
Ender tank can't be craft, cause by mek tank nbt recipe

### ISSUE THREAD

**Issue by Isla-Liu** [NordicGamerFE/Ocean-Outlast#68]
Version:
OceanOutlast V.53.1
Description:
EnderTank can't be craft, because mekanism tank material nbt not match between player made and recipe
the player made tank nbt like:
{tier:3,mekData:{security:0}}
but recipe only match:
{tier:3}
so the tank can't be craft or something cause tank can't match

Expected Result:
should be craft and got ender tank
Script/Expert/ExtendedCrafting.zs:42 need fix something for nbt match

Actual Result:
move on extended crafter and even use JEI Shift+ auto place successful,but still can't craft ender tank

Did you add additional mods?
Sponge 7.3.0
MmmMmmMmmMmm 1.14
--most server side function mod below--
DiscordIntegration 3.0.5
Dynmap 3.1
LagGoggles 4.11-92
TickProfile 0.10
unloader 1.2.0

**Comment by NightcoreIsla** [comment]
i replace the withTag to onlyWithTag then ender tank craft now
but still without other test
`#Recipe and removal for ender tank/chest
recipes.remove(<enderstorage:ender_storage:1>);
mods.extendedcrafting.TableCrafting.addShaped(0, <enderstorage:ender_storage:1>, 
[[null, null, <ore:dropHoney>, <ore:dropHoney>, <ore:dropHoney>, null, null], 
[<redstonearsenal:material:193>, <redstonearsenal:material:193>, <wrcbe:wireless_logic>, <wrcbe:sniffer>, <wrcbe:wireless_logic:1>, <redstonearsenal:material:193>, <redstonearsenal:material:193>], 
[<redstonearsenal:material:193>, <botania:elfglass>, <mekanism:machineblock2:11>.onlyWithTag({tier: 3}), <mekanism:machineblock2:11>.onlyWithTag({tier: 3}), <mekanism:machineblock2:11>.onlyWithTag({tier: 3}), <botania:elfglass>, <redstonearsenal:material:193>], 
[<botania:exchangerod>.withTag({}), <botania:elfglass>, <mekanism:machineblock2:11>.onlyWithTag({tier: 3}), <mekanism:machineblock2:11>.onlyWithTag({tier: 3}), <mekanism:machineblock2:11>.onlyWithTag({tier: 3}), <botania:elfglass>, <botania:exchangerod>.withTag({})], 
[<botania:exchangerod>.withTag({}), <botania:elfglass>, <mekanism:machineblock2:11>.onlyWithTag({tier: 3}), <mekanism:machineblock2:11>.onlyWithTag({tier: 3}), <mekanism:machineblock2:11>.onlyWithTag({tier: 3}), <botania:elfglass>, <botania:exchangerod>.withTag({})], 
[<botania:exchangerod>.withTag({}), <botania:elfglass>, <mekanism:machineblock2:11>.onlyWithTag({tier: 3}), <mekanism:machineblock2:11>.onlyWithTag({tier: 3}), <mekanism:machineblock2:11>.onlyWithTag({tier: 3}), <botania:elfglass>, <botania:exchangerod>.withTag({})], 
[<redstonearsenal:material:193>, <redstonearsenal:material:193>, <redstonearsenal:material:193>, <ic2:te:39>, <redstonearsenal:material:193>, <redstonearsenal:material:193>, <redstonearsenal:material:193>]]);
`

**Comment by NordicGamerFE** [comment]
Oredicted both tanks states
