### ISSUE TITLE
Several achievements aren't working

### ISSUE THREAD

**Issue by QueeenJane** [NordicGamerFE/Ocean-Outlast#73]
Version: 54

Description:
Several of the achievements won't acknowledge they are done. 
The first one is the emerald armor, i have the complete armor on me and it doesn't give me the achievement. 
The second one is with the steel production, you can't make the steel dust it gives you steel blend.

Expected Result:
Give rewards

Actual Result:
doesn't do anything

Did you add additional mods?
yes
Added Twitch chat integrations and Chat Tweaks

**Comment by QueeenJane** [comment]
The basic Fluid tank achievement doesn't work as well.

**Comment by WaterMelwin** [comment]
Please specify what difficulty of the pack and steel production bug has already been posted about.

**Comment by whitety22** [comment]
Has there been an update to the Steel Blend / Steel Dust issue? I am having the same experiences

**Comment by WaterMelwin** [comment]
> Has there been an update to the Steel Blend / Steel Dust issue? I am having the same experiences

no but you can just spawn in a steel dust and complete the quest.

**Comment by KonchokDhondrub** [comment]
Quest with requirement of Steel Dust can be fixed by changing (_/ftbquests editing_mode_) value (_right click on Steel Dust_) of NBT mode:**ignore** in quest book.
Same with the the quest Basic Fluid Tank from Mekanism.

**Comment by FagSoft** [comment]
The following Thermal Expansion quests have the same issue with the NBT mode needing to be set to "ignore":
 - Thermal Mediator
 - Aqueous Accumulator
 - Aquatic Entangler
 - Magmatic Dynamo (Basic)
 - Steam Dynamo (Basic)

**Comment by FagSoft** [comment]
The Ender IO machines quests have the same issue with the NBT tags. Note that this is only an issue if you've crafted and placed the machines, prior to unlocking the quests, and then try to pick them up again for the quest rewards.

**Comment by NordicGamerFE** [comment]
V 56 fixed some of these its not on ATL yet because of time restriction you can download this update manually. @FagSoft Place the EnderIO machine in a crafting grid to covert it to default WARNING this will delete everything in the machine so make sure its dont have any upgrades or items in it
