### ISSUE TITLE
Steel Production Quest wrong item-mod bug (dangit repost sorry)

### ISSUE THREAD

**Issue by CheesyButler95** [NordicGamerFE/Ocean-Outlast#75]
Version: Expert - V.54

Description:
The 'Steel Production' Quest requires the item 'Steel Dust' item from the Mekanism mod, which is unattainable, instead of the 'Steel Blend' item from Thermal Foundation.

Did you add additional mods?
No.

**Comment by Otuxoda** [comment]
So is this being looked into or?? Having same issue - same as the bed quest - no matter what bed you make you can't get the rewards. It seems to be quests that have one more quests after that is bugged eg bed into sleeping bag, steel dust into flint.

**Comment by sam-jeffs** [comment]
also having this problem :(

**Comment by witekblach** [comment]
Also having this problem, I think the item is duplicated. here is how I know its duplicated:
I'm running ocean outlast without any additional mods from AtLauncher on Ubuntu. I'm running a server(also form AtLauncher) on which I play locally on LAN :)
I tried giving myself this item so I can complete this quest with this command:
`/give my_player_name mekanism:otherdust`
I found this `mekanism:otherdust` to be the item ID from minecraft itself (tip on how to do it is [here](https://gaming.stackexchange.com/questions/360383/how-do-i-get-modded-item-block-ids) )
When I greped the whole folder with `mekanism:otherdust` I found some weird item names :/
In the end if you have access to console you can try
`/give my_player_name mekanism:otherdust 1 1`
`/give my_player_name mekanism:otherdust 1 2`
`/give my_player_name mekanism:otherdust 1 3`
`/give my_player_name mekanism:otherdust 1 4`
`/give my_player_name mekanism:otherdust 1 5`
`/give my_player_name mekanism:otherdust 1 6`
and one of these will give you the item and finish the quest :+1: 

EDIT: one of the items given was crashing the game for me when I interacted with it, my solution was to `/clear` my inventory from the servers command.
