### ISSUE TITLE
Wub-Wub Hammer grass-break crash

### ISSUE THREAD

**Issue by CheesyButler95** [NordicGamerFE/Ocean-Outlast#78]
Version: Expert - V.54

Description:
When using the Wub Wub Hammer to break grass, sometimes, causes the game to crash. The fact that it doesn't happen every time makes me think that it likely has something to do with whether breaking the grass happens to drop an item, and I have a hunch that that somehow triggers the 3x3 mining ability of the hammer, and breaking something.

Crash Report:
[https://hastebin.com/oxudovizor.rb](url)

Did you add additional mods?
no

**Comment by cenodis** [comment]
This is most likely the same issue as in Kashdeya/Tiny-Progressions#147 and its something that needs to be fixed in the mod. Unfortunately the 1.12 version of this mod is not maintained anymore.
