### ISSUE TITLE
Silverwood saplings and Shimmerleaf are nearly impossible to obtain

### ISSUE THREAD

**Issue by cenodis** [NordicGamerFE/Ocean-Outlast#8]
Expert 1.4.7
The only way silverwood and shimmerleaf can be obtained is by having it spawn via worldgen. But due to the island based generation and the fact that the magical biome is disabled its nearly impossible to find any. And both of them are needed for quests and progression into Thaumcraft.
My suggestion would be to add these both to the void botanic miner. It makes sense and fits into the established progression tree.
No extra mods added.

**Comment by Isla-Liu** [comment]
well.. silver tree
then how about crimson? i tried find, but nothing i get
