### ISSUE TITLE
Friendly mobs' health at minimum (ScalingHealth, probably)

### ISSUE THREAD

**Issue by CheesyButler95** [NordicGamerFE/Ocean-Outlast#80]
Version: Expert - V.54

I have a couple sets of mobs around, and they've been at minimum health, for no reason. There's never been enough to cause suffocation damage, so I assume its scaling health having an issue
![2021-01-02_16 08 18](https://user-images.githubusercontent.com/76766800/104108864-8c207f00-5285-11eb-8ff2-decaffc8e4cd.png)

No extra mods added

**Comment by NordicGamerFE** [comment]
I've not seen this in a while gonna close it until someone else reports on it
