### ISSUE TITLE
Compressed sand sieving missing aluminum

### ISSUE THREAD

**Issue by CheesyButler95** [NordicGamerFE/Ocean-Outlast#83]
Version: Expert - V.54

The Compressed Sand, in the sieve, with the diamond mesh, does not drop aluminum pieces like with other meshes and un-compressed sand

No extra mods added

**Comment by hipsterbaby** [comment]
Pretty sure aluminum only drops from crushed endstone

**Comment by john13210** [comment]
endstone and sand
