### ISSUE TITLE
Crash, screen goes blue-ish for a bit and then crashes.

### ISSUE THREAD

**Issue by Magnus-Artifex** [NordicGamerFE/Ocean-Outlast#85]
Version: [Easy/Expert] [The newest one lol]

Description:
[Literally opening the world to play.]

Crash Report:
[https://paste.atlauncher.com/view/43e60dbd]
[Crash reports are located in your mc folder under "./crash-reports/"]

Did you add additional mods?
[no]

**Comment by NordicGamerFE** [comment]
Increase ram
