### ISSUE TITLE
When you die the quest book disapears

### ISSUE THREAD

**Issue by Solar-Dolphin** [NordicGamerFE/Ocean-Outlast#92]
Version: Easy current version.

Description:
I died then the quest book was deleted.

Expected Result:
the quest book not to disappear when I die.

Actual Result:
The quest book was deleted when I died.

Did you add additional mods?
[no]

[If applicable, post any reports or logs related to the bug here]

**Comment by NordicGamerFE** [comment]
Use the quest book in the inventory that is always there

**Comment by john13210** [comment]
also you can have key bind for it
