### ISSUE TITLE
Bewitchment brewing not working

### ISSUE THREAD

**Issue by wickedsharp** [NordicGamerFE/Ocean-Outlast#94]
Version: default V56

Description:
Brewing in a witch's cauldron doesn't work

Expected Result:
with the cauldron bubbling and 1k+ altar power, adding mandrake then regent (in this case snow or carrot) should make a potion that can be collected with an empty bottle

Actual Result:
brew turns brown when mandrake is added, doesn't change with regent, and isn't collectable
tried it in creative with infinite altar power with the same result 

Did you add additional mods?
no

**Comment by NordicGamerFE** [comment]
I seen this issue before try to spam the cauldron with the bottle when crafting

**Comment by wickedsharp** [comment]
Spamming the bottle doesn't help.

**Comment by djozis** [comment]
I see that both Performant and Bewitchment are in this modpack. Is this the incompatibility issue between them?: https://github.com/Um-Mitternacht/Bewitchment/issues/605
