### ISSUE TITLE
Mobs spawning despite light levels being 8+

### ISSUE THREAD

**Issue by FagSoft** [NordicGamerFE/Ocean-Outlast#95]
Version: 0.54 Expert

Description:
When I'm in my base mobs keep spawning in it, despite lighting levels being above 8. I'm not doing anything special when this happens, other than spending some time crafting stuff. All of a sudden I get a deluge of mobs, most of the time about 3-4 zombies. They spawn from both the levels above and below me, if possible. Some times I also get blizz spawning in my base, not sure if there has been any other mobs though. (Besides the cyan flowers, but I suspect that's something else.

It's on a platform, so there is no other way inside my base.

Expected Result:
No mobs spawning inside my base.

Actual Result:
Overrun by mobs when crafting.

Did you add additional mods?
No.

No bug reports, but I can provide a download of/access to my world if that would help.

**Comment by FagSoft** [comment]
I can now confirm that this isn't just limited to that one instance. Have the same thing happening on a SMP I set up with some friends of mine.

Blizz spawning all of the base after a few days, then when the world difficulty gets high enough Zombies start to spawn as well. Also had a couple of instances of Black Dogs spawning inside the lit area, and a couple of the Fish's Undead Rising ones too.

I even had 3 zombies spawn in the area where the cows are now, while I was looking at them. At this point the world difficulty was at 41.72, and my personal difficulty at around 3. (All of the torches were placed when the zombies spawned.)

![image](https://user-images.githubusercontent.com/3675554/118272662-3bcf5d00-b4c3-11eb-938f-a65fb402f8e7.png)

**Comment by NordicGamerFE** [comment]
Note: Check SH Config
